# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

stages:
  - stage: Build

    pool:
      name: Azure Pipelines

    jobs:
      - job: Build
        displayName: "Angular App Build"
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - task: UseDotNet@2

          - task: Npm@1
            inputs:
              command: custom
              customCommand: "install"
              workingDir: '$(System.DefaultWorkingDirectory)'
              verbose: false
            displayName: "npm install"
              
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run build"
              workingDir: '$(System.DefaultWorkingDirectory)'
              verbose: false
            displayName: "Build Angular app"
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run test"
            displayName: "Test Angular app"

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/testresults/junit/unit-test-result.xml'

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '**/testresults/coverage/code-coverage.xml'